export * from './setup-branch';
export * from './setup-clinic';
export * from './setup-department';
export * from './setup-document-type';
export * from './setup-general';
export * from './setup-hospital.js';
export * from './setup-location';
export * from './setup-location-type';
export * from './setup-ward';
